steps:
  # Install npm dependencies
  - name: 'node:14'  # Choose a suitable Node.js runtime
    entrypoint: 'npm'
    args: ['install']
    dir: './'  # Specify the path to your Node.js project directory

  # Build the project
  - name: 'node:20'  # Choose a suitable Node.js runtime
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: './'  # Specify the path to your Node.js project directory

  # Deploy the application to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']  # Adjust 'app.yaml' if needed
    dir: './'  # Specify the path to your Node.js project directory
    timeout: '1600s' # Adjust timeout as needed
