version: 2.1

orbs:
  node: circleci/node@5.0.2
  gcp-cli: circleci/gcp-cli@3.1.1

workflows:
  version: 2
  build_and_deploy_workflow:
    jobs:
      - build_and_deploy_job:
          filters:
            branches:
              only:
                - production

jobs:
  build_and_deploy_job:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build app
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - run: 
          name: Hello world
          command: echo "hello world"
      - run: 
          name: CHeck Local files
          command: ls

     
