version: 2.1

orbs:
  node: circleci/node@5.2.0
  gcp-cli: circleci/gcp-cli@3.1.1

jobs:
  build_and_deploy_job:
    docker:
      - image: ubuntu
    steps:
      - checkout      
      - run: sudo apt-get install curl
      - node/install:
          install-yarn: true
          node-version: 'latest'
      - run: node --version

workflows:
  build_and_deploy_workflow:
    jobs:
      - build_and_deploy_job:
          filters:
            branches:
              only:
                - production