version: 2.1

workflows:
  version: 2
  build_and_deploy_workflow:
    jobs:
      - build_and_deploy_job:
          filters:
            branches:
              only:
                - production

jobs:
  build_and_deploy_job:
    docker:
      - image: ubuntu
    steps:
      - run: 
          name: hello world
          command: echo "hello world"

     
