name: Deploy to App Engine
run-name: Deploying application to App Engine

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/392632175768/locations/global/workloadIdentityPools/githubactions/attribute.repository/SummySumanth/SummySumanth.github.io'
        service_account: 'github-actions@summy-portfolio-live.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v2'

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.version_url }}"'