name: App Engine Deployer
run-name: Deploy to App Engine

on:
  push:
    tags: [ 'v*.*.*' ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  CheckoutRepo:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
  SetupNode:
    name: Setup NodeJs
    runs-on: ubuntu-latest
    needs: CheckoutRepo
    steps:
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Clean Installing NPM Packages
        run: npm ci
  Build:
    name: Build
    runs-on: ubuntu-latest
    needs: SetupNode
    steps:
      - name: Building Frontend Files
        run: npm run build
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - run: npm test
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: Tests
    steps:
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}  
    - name: Test Deployment Job
      run: curl "${{ steps.deploy.outputs.url }}"
