name: "Deploy to Google App Engine"
on:
  push:
    branches: [production]
jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Build Frontend Files
        run: npm run build
      - name: GCP Authenticate
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: '${{ env.GCP_PROJECT }}'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy to GAE
        run: gcloud app deploy app.yaml