name: "Deploy to Google App Engine"
on:
  push:
    branches: [production]
jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Build Frontend Files
        run: npm run build
      - name: GCP Authenticate
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: "273.0.0"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Set GCP_PROJECT
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: gcloud --quiet config set project ${GCP_PROJECT}
      - name: Deploy to GAE
        run: gcloud app deploy app.yaml